name: 'Azure Pipelines'

trigger:
  batch: true
  branches:
    include:
    - main
pr:
  autoCancel: false
  branches:
    include:
    - main

variables:
  DOTNET_NOLOGO: true
  Solution_File: $(System.DefaultWorkingDirectory)/source/F0.Minesweeper.sln
  NuGet_Configuration_File: $(System.DefaultWorkingDirectory)/source/nuget.config
  Build_Configuration: 'Release'

jobs:
- job: A
  displayName: string
  pool:
    vmImage: 'ubuntu-18.04'

  variables:
    TODO: TODO

  steps:
  - checkout: self
    displayName: Checkout
    fetchDepth: 1
  - task: UseDotNet@2
    displayName: Setup .NET SDK
    inputs:
      packageType: 'sdk'
      useGlobalJson: true
      performMultiLevelLookup: true
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: 'restore'
      feedsToUse: 'config'
      nugetConfigPath: '$(NuGet_Configuration_File)'
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: 'build'
      arguments: '$(Solution_File)'
  - task: DotNetCoreCLI@2
    displayName: Collect code coverage metrics with Coverlet
    inputs:
      command: 'test'
      #projects: '**/test-library/*.csproj'
      arguments: '$(Solution_File) /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=$(Build.SourcesDirectory)/TestResults/Coverage/'
      publishTestResults: true
  - task: PublishCodeCoverageResults@1
    displayName: Publish code coverage report
    inputs:
      codeCoverageTool: 'Cobertura'
      summaryFileLocation: '$(Build.SourcesDirectory)/**/coverage.cobertura.xml'
      failIfCoverageEmpty: true
