name: 'Azure Pipelines'

trigger:
  batch: false
  branches:
    include:
    - main
pr:
  autoCancel: false
  branches:
    include:
    - main

variables:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  VM_Image: 'ubuntu-20.04'
  Build_Configuration: 'Release'

jobs:
- template: templates/unit-tests.yml
  parameters:
    vmImage: ${{ variables.VM_Image }}
- template: templates/code-coverage.yml
  parameters:
    vmImage: ${{ variables.VM_Image }}
- template: templates/mutation-testing.yml
  parameters:
    vmImage: ${{ variables.VM_Image }}
