parameters:
- name: vmImage
  displayName: 'Agent'
  type: string
  default: 'windows-latest'

jobs:
- job: mutation_testing
  displayName: Mutation Testing
  pool:
    vmImage: ${{ parameters.vmImage }}

  variables:
    NuGet_Configuration_File: $(System.DefaultWorkingDirectory)/nuget.config
    Tool_Manifest_File: $(System.DefaultWorkingDirectory)/.config/dotnet-tools.json
    Stryker_Configuration_File: $(System.DefaultWorkingDirectory)/source/test/stryker-config.json
    Stryker_Working_Directory: $(System.DefaultWorkingDirectory)/scripts

  steps:
  - checkout: self
    displayName: Checkout
    fetchDepth: 1
  - task: UseDotNet@2
    displayName: Setup .NET SDK
    inputs:
      packageType: 'sdk'
      useGlobalJson: true
      performMultiLevelLookup: true
  - task: DotNetCoreCLI@2
    displayName: Install .NET Tools
    inputs:
      command: 'custom'
      custom: 'tool'
      arguments: 'restore --configfile $(NuGet_Configuration_File) --tool-manifest $(Tool_Manifest_File) --no-cache'
  - task: DotNetCoreCLI@2
    displayName: Run dotnet-stryker
    inputs:
      command: 'custom'
      custom: 'stryker'
      arguments: '--config-file $(Stryker_Configuration_File)'
      workingDirectory: '$(Stryker_Working_Directory)'
  - task: PublishMutationReport@0
    displayName: Publish Mutation Test Report
    inputs:
      reportPattern: '**/mutation-report.html'
