parameters:
- name: vmImage
  displayName: 'Agent'
  type: string
  default: 'windows-latest'

jobs:
- job: unit_tests
  displayName: Unit Tests
  pool:
    vmImage: ${{ parameters.vmImage }}

  variables:
    Solution_File: $(System.DefaultWorkingDirectory)/source/F0.Minesweeper.sln
    NuGet_Configuration_File: $(System.DefaultWorkingDirectory)/nuget.config

  steps:
  - checkout: self
    displayName: Checkout
    fetchDepth: 1
  - task: UseDotNet@2
    displayName: Setup .NET SDK
    inputs:
      packageType: 'sdk'
      useGlobalJson: true
      performMultiLevelLookup: true
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: 'restore'
      restoreArguments: '$(Solution_File)'
      feedsToUse: 'config'
      nugetConfigPath: '$(NuGet_Configuration_File)'
      verbosityRestore: 'Minimal'
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: 'build'
      arguments: '$(Solution_File) --no-restore --nologo'
  - task: DotNetCoreCLI@2
    displayName: Generate Test Results
    inputs:
      command: 'test'
      arguments: '$(Solution_File) --no-build --nologo --logger trx'
      publishTestResults: false
  - task: PublishTestResults@2
    displayName: Publish Test Results
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: '**/*.trx'
      mergeTestResults: true
