name: Restore + Build + Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  restore_build_test:
    name: on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        configuration: [Release]
        os: [macos-11, ubuntu-20.04, windows-2022]

    env:
      NuGet_Configuration_File: ./nuget.config
      Solution_File: ./source/F0.Minesweeper.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1.7.2
    - name: Restore
      run: dotnet restore ${{ env.Solution_File }} --configfile ${{ env.NuGet_Configuration_File }}
    - name: Build
      run: dotnet build ${{ env.Solution_File }} --configuration ${{ matrix.configuration }} --no-restore --nologo
    - name: Test
      run: dotnet test ${{ env.Solution_File }} --configuration ${{ matrix.configuration }} --no-build --nologo
